apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: python-app
  description: Python-app displys time and hostnme.
  annotations:
    github.com/project-slug: andrew-liu1982/python-app
  #   backstage.io/techdocs-ref: dir:.
spec:
  type: service
  owner: user:liuzhiyong.1982@kubecanops.win
  lifecycle: experimental